// 오프닝 스토리 데이터. 1000점을 넘길 때마다 챕터가 하나씩 재생된다.
// type: 'narration'(내레이션) | 'speech'(정민의 말/속마음) | 'system'(상태창)
const HUMAN = 'human';
const GOBY = 'goby';

const STORY_CHAPTERS = [
  {
    portrait: HUMAN,
    lines: [
      { type: 'narration', text: '광평로 51길에 사는 박정민은 자신이 정상적이라는 것을 아주 자랑스럽게 여기는 사람이었다. 그는 기이하거나 신비스러운 일과는 전혀 무관해 보였다. 아니, 그런 터무니없는 것은 도저히 참아내지 못했다.' },
      { type: 'narration', text: '다만 한 가지, 남들이 이해하지 못 하는 취미가 있었다.' },
      { type: 'narration', text: '망둑어.' },
      { type: 'narration', text: '누군가는 TRPG를 하고, 보드게임을 하고, 덕질을 했다.' },
      { type: 'narration', text: '하지만 정민은 갯벌에 쪼그려 앉아 망둑어를 관찰했다.' },
      { type: 'narration', text: '진흙 위에서 튀어나온 눈을 껌뻑이며 세상을 경계하던 말뚝망둥어.' },
      { type: 'narration', text: '물살이 완만한 하천 하구에서 바닥을 기어다니던 풀망둑.' },
      { type: 'narration', text: '잔잔한 방파제 아래에서 낚싯바늘을 툭툭 건드리던 문절망둑.' },
      { type: 'narration', text: '그 작은 생물들을 바라보고 있으면 시간 가는 줄을 몰랐다. 정민에게 망둑어는 흔한 물고기가 아니다. 바닥을 정리하고, 모래를 뒤집고, 눈에 띄지 않는 자리에서 생태를 지탱하는 존재. 화려하지도, 크지도 않지만 묵묵히 제 역할을 다 하는 생물. 깊은 바닷속에서도, 갯벌에서도 살아가는 망둑어가 있다는 점도 흥미로웠다.' },
      { type: 'narration', text: '그리고, 좋아하니까 맛도 궁금했다.' },
      { type: 'speech', text: '"생각보다 단단하네. 바닥 생활을 해서 그런가?"' },
      { type: 'narration', text: '낚시로 잡은 망둑어로 매운탕을 끓여 먹으며 그는 진지하게 식감을 분석하고 있었다.' },
    ],
  },
  {
    portrait: HUMAN,
    lines: [
      { type: 'narration', text: '퇴근 후에는 또 다른 바다가 그를 기다리고 있었다.' },
      { type: 'narration', text: '거실 한 켠에 놓인 해수어항. 푸른 LED 조명 아래에서 산호가 천천히 흔들리고, 작은 해수어들이 그 사이를 유영했다. 그 속에 특히 눈에 밟히는 존재가 있었다.' },
      { type: 'narration', text: '바닥에서 끊임없이 모래를 퍼먹는 길쭉한 몸뚱이.' },
      { type: 'narration', text: '다이아몬드 고비.' },
      { type: 'narration', text: '입 안 가득 모래를 머금었다, 아가미로 고운 입자만을 흩뿌린다. 그 동작은 단순하지만 경이로웠다. 그 덕에 해수어항의 바닥은 늘 이끼 없이 깨끗했다. 종종 입에 맞지 않는 모래를 삼키면 퉤, 하고 뱉어내는 모습도 너무 귀여웠다.' },
      { type: 'narration', text: '정민은 수조에 이마를 기대고 중얼거렸다.' },
      { type: 'speech', text: '"어쩜 이렇게 부지런하니... 다이아몬드 고비 열 마리만 있었더라면, 아틀란티스도 묻을 수 있었을 거야."' },
      { type: 'narration', text: '물론 다른 고비들도 사랑했다.' },
      { type: 'narration', text: '피스톨 쉬림프와 나란히 굴을 지키던 랜달 고비,' },
      { type: 'narration', text: '화려한 색감의 파이어 고비,' },
      { type: 'narration', text: '산호 틈에서 영역을 사수하던 약간은 소심한 옐로우 락 고비.' },
      { type: 'narration', text: '그러나 결국 그의 시선은 바닥으로 돌아왔다.' },
      { type: 'narration', text: '모래를 먹고, 걸러내고, 다시 쌓는 존재. 그 단순한 반복 속에 이상한 안정감이 있었다.' },
    ],
  },
  {
    portrait: HUMAN,
    lines: [
      { type: 'narration', text: '여름 휴가가 시작되자마자, 정민은 주저하지 않고 동남아시아행 비행기를 탔다. 목적은 단 하나, 자연 속 고비 관찰.' },
      { type: 'narration', text: '수면 아래에 발을 담근 순간, 세상은 완전히 달라졌다.' },
      { type: 'narration', text: '빛은 물결에 부서져 흩어졌고, 산호 군락은 거대한 도시처럼 펼쳐졌다. 형형색색의 해수어들은 그 사이를 바쁘게 누비었고, 해저의 모래는 부드러운 파도에 따라 천천히 일렁였다.' },
      { type: 'narration', text: '그리고 암초 아래, 희미하게 보이는 보랏빛 실루엣.' },
      { type: 'speech', text: '\'이렇게 얕은 곳에 헬프리치 고비가..?\'' },
      { type: 'narration', text: '정민의 심장이 강하게 뛰었다.' },
      { type: 'narration', text: '조금 더 가까이. 조금만 더...!' },
      { type: 'narration', text: '수압이 조금씩 강해졌다. 귀 안쪽이 먹먹해졌다. 하지만 눈앞의 작고 화려한 고비는 선명하게 보였다.' },
    ],
  },
  {
    portrait: HUMAN,
    lines: [
      { type: 'narration', text: '그 때, 공기의 흐름이 끊겼다.' },
      { type: 'narration', text: '산소 게이지가 비정상적으로 흔들렸다.' },
      { type: 'speech', text: '\'어...?\'' },
      { type: 'narration', text: '심장이 덜컥 내려앉았다.' },
      { type: 'narration', text: '정민은 상승을 시도했으나 무언가에 걸렸는지 몸이 말을 듣지 않았다. 물살은 생각보다 거셌고, 시야는 점점 흐려졌다. 숨이 차오르며 폐가 타는 듯했다.' },
      { type: 'narration', text: '마지막으로 본 것은 암초 아래 고개를 내밀고 있던 작은 고비 한 마리였다.' },
      { type: 'narration', text: '그 동그란 눈이 이상하리만치 또렷하게 기억에 남았다.' },
    ],
  },
  {
    portrait: GOBY,
    lines: [
      { type: 'narration', text: '...무언가 입안에서 부서졌다.' },
      { type: 'narration', text: '잘게 으스러진 알갱이들이 흩어졌고, 짭짤한 바닷물과 뒤섞여 묘한 흙맛을 남겼다.' },
      { type: 'narration', text: '정민은 천천히 주변을 살폈다. 시야가 낮았다. 지나치게 낮았다.' },
      { type: 'narration', text: '눈앞의 모래 한 알이 바위처럼 커다랗게 보였고, 그 사이를 흐르는 물살은 계곡물처럼 느껴졌다. 빛은 위에서 비스듬히 내려오고 있었다.' },
      { type: 'speech', text: '\'뭐지...?\'' },
      { type: 'narration', text: '몸을 움직이려는 순간, 낯선 감각이 전해졌다.' },
      { type: 'speech', text: '팔이 없다!' },
      { type: 'narration', text: '대신 얇고 짧은 지느러미가 파닥였다. 허리가 좌우로 흔들리면 몸이 미끄러지듯 움직였다.' },
      { type: 'narration', text: '그리고 다시... 나도 모르게 모래를 삼켰다.' },
      { type: 'narration', text: '쩝쩝... 모래가 입 안 가득 들어왔다.' },
      { type: 'narration', text: '본능적으로 아가미가 움직였다. 고운 모래는 부드럽게 빠져나가고, 거친 유기물만 남았다.' },
      { type: 'narration', text: '한 번 더 모래를 삼켰다. 완벽하게 걸러졌다. 바닥이 깨끗해졌다.' },
      { type: 'speech', text: '\'모래 속 유기물은 이런 맛이었구나!\'' },
      { type: 'narration', text: '그 순간, 머릿속 어딘가에서 기계적인 문장이 울리며, 눈앞에 상태창이 나타났다.' },
      { type: 'system', text: '[패시브 스킬 획득]\n모래먹기 Lv.1\n바닥의 모래를 섭취하여 영양분과 미네랄을 추출합니다.' },
    ],
  },
  {
    portrait: GOBY,
    lines: [
      { type: 'speech', text: '"...."' },
      { type: 'narration', text: '말하려 했지만 기포만 올라왔다.' },
      { type: 'narration', text: '그는 천천히 몸을 틀어 자신의 그림자를 바라보았다.' },
      { type: 'narration', text: '길쭉한 몸뚱이, 지느러미로 바닥에 선 자세, 둥근 눈. 그리고 입가의 모래.' },
      { type: 'narration', text: '심장이 뛰었다.' },
      { type: 'speech', text: '\'나... 고비가 된 거야...? 정말... 내 소원이 이루어졌구나...!\'' },
      { type: 'narration', text: '정민은 기쁨에 미친 듯이 모래를 삼켰다.' },
      { type: 'speech', text: '\'퉤!\'' },
      { type: 'narration', text: '역겨운 맛이 났다. 누군가의 똥을 삼킨 듯했다. 정민의 해수어항의 다이아몬드 고비는 가끔 모래를 입으로 뱉어내곤 했는데, 이제 그 이유를 알 것 같았다.' },
      { type: 'narration', text: '정민은 계속 모래를 먹었다.' },
      { type: 'narration', text: '입안에서 모래가 부서질 때마다, 묘한 안정감이 밀려왔다. 마치 제 자리를 찾은 것처럼. 모래를 정리하고 있다는 감각. 바닥을 고르고 있다는 감각이 이상하게 만족스러웠다.' },
    ],
  },
  {
    portrait: GOBY,
    lines: [
      { type: 'narration', text: '그때, 지면 아래에서 미세한 진동이 느껴졌다.' },
      { type: 'narration', text: '쾅!' },
      { type: 'narration', text: '바다가 통째로 흔들리는 것 같았다.' },
      { type: 'narration', text: '충격파가 모래를 걷어 올렸다. 정민은 반사적으로 몸을 낮추었다.' },
      { type: 'narration', text: '산호초 옆에서 노란 눈이 번득였다. 그 옆에는 커다란 집게를 치켜 든 새우 한 마리.' },
      { type: 'speech', text: '영역 침범.' },
      { type: 'narration', text: '본능이 경고했다.' },
      { type: 'narration', text: '두 번째 충격이 울리기 전, 정민은 몸을 틀어 모래 위를 미친 듯이 달렸다. 심장이 빠르게 뛰었다. 등 뒤에서 물살이 밀려왔다.' },
      { type: 'narration', text: '한참을 도망친 후에야 숨을 고를 수 있었다.' },
      { type: 'narration', text: '그 순간, 다시 상태창과 목소리가 떠올랐다.' },
      { type: 'system', text: '[특성 분석 완료]\n상호작용한 생명체의 특성 일부를 복사할 수 있습니다.\n\'망보기\' 습득 - 옐로우와치맨고비\n\'충격파 발사(약)\' 습득 - 피스톨 쉬림프' },
    ],
  },
  {
    portrait: GOBY,
    lines: [
      { type: 'narration', text: '정민은 고개를 들었다.' },
      { type: 'narration', text: '시야가 넓어졌다. 주변의 움직임이 또렷하게 감지됐다. 모래 아래의 미세한 진동까지 읽히는 느낌.' },
      { type: 'narration', text: '입 안 깊숙한 곳에서도 미세한 진동이 느껴졌다.' },
      { type: 'speech', text: '\'설마 나도?\'' },
      { type: 'narration', text: '그는 조심스럽게 턱을 움직였다. 아주 작은 충격파가 앞으로 번졌다. 모래가 살짝 들썩였다.' },
      { type: 'narration', text: '정민은 흥분되기 시작했다.' },
      { type: 'narration', text: '망둑어로 전생했다. 그것도, 특성을 복사하는 고비로.' },
      { type: 'narration', text: '수면에서는 햇빛이 부서지고 있었다. 아래에는 끝없이 펼쳐진 모래 바닥. 그리고 자신은 그 위에 엎드려 있었다.' },
      { type: 'narration', text: '정민은 천천히 모래를 한 입 더 삼켰다.' },
      { type: 'narration', text: '짭짤하고, 고요하고, 이상하게도 편안한 맛이었다.' },
      { type: 'narration', text: '평생을 꿈꿔왔던, 모래를 먹는 작은 물고기의 삶이 시작되었다.' },
    ],
  },
];
